BE-1501: added audiences support for fulfilment models
realifetech/python-sdk pull request #16
Opened 2021-07-12 07:45 UTC by slava-petrov

2021-07-13 08:45 UTC, tomrutherford-livestyled requested changes

2021-07-13 08:45 UTC, tomrutherford-livestyled commented on livestyled/models/fulfilment_point.py
> +        for audience in audiences:
I don't think this is required, its a half attempt at field validation

I could still call this function with [12, 'user_management/audiences/2', 'somerandomiri/13'] and that would be valid. Lets just make the function require an array of iri's and not do any specific formatting.

2021-07-13 09:46 UTC, ndy40 requested changes

2021-07-13 09:46 UTC, ndy40 commented on livestyled/models/fulfilment_point.py
> +        self.audiences = audiences
I think you need to do the same thing like `categories` below.

2021-07-13 09:46 UTC, ndy40 commented on livestyled/models/fulfilment_point.py
> +        self.audiences = audiences
You also need to update the `schema/fulfilment_point.py`, the Audience needs a schema like 
`categories = RelatedResourceField(schema=FulfilmentPointCategorySchema, many=True, missing=[])`. You need to attache an AudienceSchema to it.

2021-07-14 15:29 UTC, ndy40 requested changes

2021-07-14 15:29 UTC, ndy40 commented on livestyled/schemas/fulfilment_point.py
> +    audiences = RelatedResourceField(schema=AudienceSchema, many=True, missing=[])
Have you tested this? I thought this should be `RelatedResourceLinkField`  like the others. please write a test to make sure this works.

2021-07-19 12:55 UTC, tomrutherford-livestyled approved these changes

2021-07-19 12:55 UTC, merged