CTD-130 add search by order number to order model
realifetech/python-sdk pull request #36
Opened 2021-09-09 12:18 UTC by DashaSyvyuk

2021-09-09 12:30 UTC, Edvinas9 commented on livestyled/resource_client.py
> +            return self._get_resource_list(OrderSchema, filters=filter_param)
I think these 4 lines could be simplified to:
`return self._get_resource_list(OrderSchema, filters=filter_param or None)`

2021-09-09 12:37 UTC, Edvinas9 approved these changes

2021-09-10 13:32 UTC, ndy40 commented on livestyled/resource_client.py
> +        return self._get_resource_list(OrderSchema, filters=filter_param or None)
why are we passing saying `filter_param or None` ? I think if empty, this should still work.

2021-09-10 14:24 UTC, ndy40 requested changes

2021-09-10 14:24 UTC, ndy40 commented on livestyled/models/order.py
> +        fields = (
can fit in one line. What of the other properties. We should just solve this problem at once so we don't have to come back to add it later.

2021-09-13 09:02 UTC, ndy40 approved these changes

2021-09-13 09:02 UTC, merged